### ISSUE TITLE
Not enough information provided

### ISSUE THREAD

**Issue by zpallin** [baigm/Linux-uptime#2]
The output here is not quite detailed enough.

`root@server:~/Programs/Linux-uptime$ python json_uptime.py`
`{"uptime": "2"}`

The number value here is 2, but the value is not entirely apparent. Imagine I am writing an app that needs to get any of the many values supplied by a typical "uptime" call, I would not have enough information here.

A typical uptime output looks like this:
`16:58:19 up 21 days, 21:19,  3 users,  load average: 0.06, 0.06, 0.08`

I can see a few keys I would want provided as a result of this.
1. The time that the uptime was run (in this case 16:58:19)
2. How many days + hours it has been up.
3. How many users are logged in.
4. And the load averages over the last 1 minute, 5 minutes, and 15 minutes.

**Comment by baigm** [comment]
I've gone ahead and updated the script to parse and return the requested information. 
Please go ahead and test.

**Comment by zpallin** [comment]
Excellent. Worked perfectly
